/* !!IMPORTANT 
   This file has been automatically generated 
*/

module.exports = {
  /* #below rules from 'eslintVueAdjust.js'# */
  "vue/html-closing-bracket-spacing": "error",
  "vue/html-end-tags": "error",
  "vue/html-indent": "error",
  "vue/html-quotes": "error",
  "vue/html-self-closing": "error",
  "vue/max-attributes-per-line": "off",
  "vue/no-spaces-around-equal-signs-in-attribute": "error",
  "vue/no-template-shadow": "error",
  "vue/prop-name-casing": "error",
  "vue/require-default-prop": "off",
  "vue/require-prop-types": "off",
  "vue/singleline-html-element-content-newline": "off",
  "vue/mustache-interpolation-spacing": "error",
  "vue/no-multi-spaces": "error",
  "vue/v-bind-style": "off",
  "vue/v-on-style": "error",
  "vue/attributes-order": "off",
  "vue/order-in-components": "off",
  /* #below rules from 'eslintVueRules.js'# */
  "vue/comment-directive": "error",
  "vue/jsx-uses-vars": "error",
  "vue/no-async-in-computed-properties": "error",
  "vue/no-dupe-keys": "error",
  "vue/no-duplicate-attributes": "error",
  "vue/no-reserved-keys": "error",
  "vue/no-shared-component-data": "error",
  "vue/no-side-effects-in-computed-properties": "error",
  "vue/no-template-key": "error",
  "vue/no-textarea-mustache": "error",
  "vue/no-unused-components": "error",
  "vue/no-unused-vars": "error",
  "vue/no-use-v-if-with-v-for": "error",
  "vue/require-component-is": "error",
  "vue/require-prop-type-constructor": "error",
  "vue/require-render-return": "error",
  "vue/require-v-for-key": "error",
  "vue/require-valid-default-prop": "error",
  "vue/return-in-computed-property": "error",
  "vue/use-v-on-exact": "error",
  "vue/valid-template-root": "error",
  "vue/valid-v-bind": "error",
  "vue/valid-v-cloak": "error",
  "vue/valid-v-else-if": "error",
  "vue/valid-v-else": "error",
  "vue/valid-v-for": "error",
  "vue/valid-v-html": "error",
  "vue/valid-v-if": "error",
  "vue/valid-v-model": "error",
  "vue/valid-v-on": "error",
  "vue/valid-v-once": "error",
  "vue/valid-v-pre": "error",
  "vue/valid-v-show": "error",
  "vue/valid-v-text": "error",
  "vue/attribute-hyphenation": "warn",
  "vue/html-closing-bracket-newline": "warn",
  "vue/multiline-html-element-content-newline": "warn",
  "vue/name-property-casing": "warn",
  /* #below rules from 'eslintVueExtra.js'# */
  "vue/arrow-spacing": "error",
  "vue/block-spacing": "error",
  "vue/brace-style": "error",
  "vue/comma-dangle": "off",
  "vue/key-spacing": "error",
  "vue/object-curly-spacing": "off",
  "vue/script-indent": "error",
  "vue/space-infix-ops": "off",
};